#!/bin/sh /etc/rc.common
START=99
STOP=10
USE_PROCD=1

CONF="/etc/sb-shunt/config.json"

start_service() {
  [ -f "$CONF" ] || exit 0
  /usr/bin/sb-shunt --apply-fw >/dev/null 2>&1 || true

  procd_open_instance
  procd_set_param command /usr/bin/sing-box run -c "$CONF"
  procd_set_param respawn 3600 5 5
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}

reload_service() {
  stop
  start
}
